name: Build and test

on: push

env:
  Configuration: Release
  TestResultsDirectory: TestResults

jobs:

  BuildAndTest:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: .\Build.ps1 -Build -Configuration "${{ env.Configuration }}"

    - name: Test
      run: .\Build.ps1 -Test -Configuration "${{ env.Configuration }}" -TestResultsDirectory "${{ env.TestResultsDirectory }}"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: ${{ env.TestResultsDirectory }}
      if: ${{ always() }}